services:
  couchdb:
    image: couchdb:2.1.1
    volumes:
      - "/srv/vi/conf:/opt/couchdb/etc/local.d"
      - "/srv/vi/data:/opt/couchdb/data"
      - "/srv/vi/log:/opt/couchdb/var/log"
  db-init:
    image: treehouses/planet:db-init-0.1.5
    depends_on:
      - couchdb
    environment:
      - COUCHDB_HOST=http://couchdb:5984
  planet:
    image: treehouses/planet:0.1.5
    environment:
      - HOST_PROTOCOL=https
      - DB_HOST=vi.media.mit.edu
      - DB_PORT=2200
    depends_on:
      - couchdb
  proxy:
    image: nginx:1.13
    volumes:
      - ./out/vi.media.mit.edu/:/etc/nginx/certs/vi.media.mit.edu/
      - ./configs/app.conf:/etc/nginx/conf.d/app.conf
    depends_on:
     - planet
    ports:
     - "80:80"
     - "443:443"
     - "2200:2200"
     - "2201:2201"
version: "2"
